### ISSUE TITLE
Desktop file issues

### ISSUE THREAD

**Issue by paravoid** [agalakhov/xiccd#12]
While preparing an updated Debian package for 0.2.4, I found the following issues:
- Upstream autoconf installs the .desktop file to `/usr/share/applications`, not `/etc/xdg/autostart`. Is that intentional? That's contrary to what the manpage suggests and would mean that xiccd can only be invoked manually, right?
- `Encoding` is [deprecated by FreeDesktop](https://standards.freedesktop.org/desktop-entry-spec/1.1/apc.html) and needs to be dropped (lintian's [desktop-entry-contains-encoding-key](https://lintian.debian.org/tags/desktop-entry-contains-encoding-key.html))
- Instead of using `OnlyShowIn=XFCE;MATE;LXDE;` we could use `NotShowIn=GNOME;KDE;` (lintian's [desktop-entry-limited-to-environments](https://lintian.debian.org/tags/desktop-entry-limited-to-environments.html))
- Lintian thinks that no main categories are being used but additional are ([desktop-entry-lacks-main-category](https://lintian.debian.org/tags/desktop-entry-lacks-main-category.html)). I think we can just drop the empty `Categories=` line?
- Finally, lintian complains about the lack of `Keywords` and `Icon`, but I think these may be quite useless for the case of a non-menu .desktop file that's only used for autostart.

**Comment by agalakhov** [comment]
Thanks, I'll update it. It is just outdated.

**Comment by paravoid** [comment]
Awesome, thank you both! I'll wait for the next release, any ideas on when this may happen?

**Comment by agalakhov** [comment]
I'll do it ASAP after some testing. It would be probably even 0.3.0.
