### ISSUE TITLE
GLib-GObject-CRITICAL

### ISSUE THREAD

**Issue by es20490446e** [agalakhov/xiccd#19]
In the application "terminal", if I enter "xiccd", I get various lines of the following message:

`(xiccd:8907): GLib-GObject-CRITICAL **: 02:49:25.337: g_object_unref: assertion 'G_IS_OBJECT (object)' failed`

Although the daemon still works.

**Comment by agalakhov** [comment]
Thank you.

**Comment by es20490446e** [comment]
You are welcome ;)
