### ISSUE TITLE
Systemd support

### ISSUE THREAD

**Issue by es20490446e** [agalakhov/xiccd#20]
If I created a Systemd service for Xiccd, so it's more practical to start and stop it, would you include it in this repository?

**Comment by agalakhov** [comment]
Of course! Do you have such a file? Please send me a pull request.

**Comment by es20490446e** [comment]
It's mostly finished. I'll send you it when I'm done!

**Comment by es20490446e** [comment]
There's a thing I needed to know. When in the terminal I enter:
`xiccd`

The program seems available for displaycal to use. But if I enter:
`sudo xiccd`

It doesn't see it. What could the reason be?

**Comment by agalakhov** [comment]
`xiccd` speaks to the user's X server (like a normal X client). One can't start `xiccd` if no user is logged in, and one must start `xiccd` from the same user as the X session with proper `DISPLAY=` set. It belongs to the user's autostart session, not to the global one. So no, you can't start `xiccd` as root and you can't start `xiccd` from some third user. You must start it together with the user's desktop environment after login.

This is the reason why `xiccd` exists. The `colord` daemon does most of color management things. But there are things that must be done from user's session. In Gnome or Cinnamon they're done by the session's settings daemon. But some DEs have no such daemon or don't support color management. A user of such a DE should start `xiccd` somewhere from session autostart. It may be done with `systemd` too, but it's not to be done in the system-_global_ `systemd`, it's user-specific and DE-specific. Most DEs use XDG autostart to do the trick.

**Comment by es20490446e** [comment]
What I'm trying to achieve is Xiccd to be started right away after installation, for any future user session. So it just works out of the box.

I know how to that with XDG autostart. But with SystemD it got it to work only if each individual user enables the service for their own session.

When I try to run it as system wide, even when I launch it for a specific user already logged in, the service doesn't work. I'm trying to figure out basically how I could make an XDG autostart with SystemD.

**Comment by agalakhov** [comment]
You should make sure that `xiccd` is started as user with the `DISPLAY=` environment variable correctly set. Do not try to start as root.

**Comment by es20490446e** [comment]
HAHAHA!

I fixed it 😛

I have also documented it in the [Arch Linux Wiki](https://wiki.archlinux.org/index.php/Systemd/User).

The attachement contains the service and an installation script, both error proofed. Have a look, and tell me what do you think.

I don't know how that could be translated into a Makefile, perhaps that's more obvious to you. If that isn't the case I can investigate it.

**Comment by es20490446e** [comment]
[service.tar.gz](https://github.com/agalakhov/xiccd/files/2139626/service.tar.gz)

**Comment by es20490446e** [comment]
Wait, I figured out a better way...

**Comment by es20490446e** [comment]
[This](https://github.com/agalakhov/xiccd/files/2168431/service.tar.gz).

**Comment by es20490446e** [comment]
Do you like the result of this prototype, or would you change something?

Basically what it does is to load xiccd after dbus. Doing before that seems to fail due to the dependency of colord on it.

If dbus is started or stopped, xiccd will also be. If xiccd crashed for any reason it will be automatically reloaded.

I liked to made it dependent of graphical-session.target, a unit that groups all graphical session units for that particular user session. But it seems it's something very new and usually not enabled in most distros these days.

**Comment by es20490446e** [comment]
@agalakhov 

I liked the service to be instantly available after installation, without the need to reboot. But this proved to be a non trivial task for any packager to perform by themselves.

So I was thinking that I could also make packaging xiccd as automated and straightforward as possible. I can make a prototype of that, and we can include only the aspects that you completely agree with.

The question is under which circumstances you think that could be a good thing? What do you personally think would be important?

**Comment by agalakhov** [comment]
This strongly depends on the distribution being used. There are at least three major package managers and at least two ways to start the daemon in user's session, and each distribution does it differently.
For now, I leave this up to distribution maintainers since they know better how their distribution works.

**Comment by es20490446e** [comment]
The question is that the composite of figuring out how to build, install and activate the software seems way too much work on the packager for xiccd in particular. That's why I'm suggesting providing all or part of the needed functions for that.

At least having a build script seems useful. Here's a [prototype](https://bin.privacytools.io/?1b9bf6886fa0e88b#a0axA3DrXINPobJp7mWhQV88VrwadZ2UVTbkWpAIpBY=) for that.

Packaging could be made standard agnostic, like this [installer](https://gitlab.com/es20490446e/exeCute/blob/master/installer).

How to start the daemon could be decided upon if the command "systemctl" is present in the system., otherwise fallback to copying the appropriate desktop file to "/etc/xdg/autostart". For the systemd part I have an unfinished [test](https://bin.privacytools.io/?cb0a7105ef14d008#WIxSrg2Pw1YtWrSK+j3OutSBXb34ROWtNCmAS1Rs3R4=).

That's a non negligible amount of code for a packager to figure out.

**Comment by es20490446e** [comment]
You choose which of those phases to provide:
- Build
- Install
- Activate

**Comment by agalakhov** [comment]
What we definitely should do is providing a standard `configure` script so that standard `make install DESTDIR=xxx` would be suitable out of the box for each packaging system.

Please note that `xiccd` should NOT run system-wide. It is a per-user daemon. This is the reason why it exists: there is system-wide `colord` which works for all users, and each user should run an instance of `xiccd` within her session. Starting of the daemon depends on the concrete configuration of X and on the user startup scripts, and `systemctl` is not so important here. Maybe even `/etc/X11/` is the correct place.

**Comment by es20490446e** [comment]
I designed the service to be run as an user service only. Perhaps I shall name it "xiccd-user.service" so that is clear for anybody packaging it.

And perhaps, thinking twice, probably I'm over engineering a little bit. And providing the service file would be enough.

I'm not familiar with writing "configure" scripts dough. I don't know if including the service file would need any modifications in that regard.

**Comment by agalakhov** [comment]
Creating the configure script requires zero effort and happens within the normal build process. It just has to be packaged. Autogenerated files like `configure` do not belong to git but should be saved in the archives. It's about archiving the release on a homepage, not about file creation.

**Comment by es20490446e** [comment]
Yeah, by knowing that is how I created the [build prototype](https://bin.privacytools.io/?1b9bf6886fa0e88b#a0axA3DrXINPobJp7mWhQV88VrwadZ2UVTbkWpAIpBY=) ;P

So the know how is build into code, no documentation needed.

**Comment by es20490446e** [comment]
Published it into a separate [repository](https://gitlab.com/es20490446e/xiccd-service).

**Comment by es20490446e** [comment]
[xiccd service.tar.gz](https://github.com/agalakhov/xiccd/files/4288847/xiccd.service.tar.gz)

**Comment by es20490446e** [comment]
Xiccd no longer launches on my system using the xdg autostart method. Launching from the terminal works though.

Please have a look at the [pull request](https://github.com/agalakhov/xiccd/pull/30).
