### ISSUE TITLE
failed to obtain org.freedesktop.color-manager.create-device auth

### ISSUE THREAD

**Issue by kanyck** [agalakhov/xiccd#32]
After a last system update I noticed that color management stoped working. Some digging showed that `xiccd` cannot create colord device anymore with the following error message: 
`(xiccd:21056): CRITICAL **: 20:19:27.520: failed to create colord device: failed to obtain org.freedesktop.color-manager.create-device auth`
I also noticed that colord is started as root, while colord user is present. I believe xiccd is responsible for starting colord, isn't it?

**Comment by agalakhov** [comment]
No, it is not. It just talks to the dbus and lets the underlying dbus stuff do the rest.
Looks like your system has misconfigured dbus service privileges (keyword: "PolicyKit"). Look at `/usr/share/dbus-1/` and `/etc/dbus-1/` for them. For example, you may have `/usr/share/dbus-1/system-services/org.freedesktop.ColorManager.service` that looks like this:
```
[D-BUS Service]
Name=org.freedesktop.ColorManager
Exec=/usr/lib/colord
User=colord
SystemdService=colord.service
```
And `/usr/share/dbus-1/system.d/org.freedesktop.ColorManager.conf` with references to PolicyKit.

**Comment by kanyck** [comment]
I'm on Gentoo, so some systemd-related stuff may easily be misconfigured somehow...
The files you mentioned are in place and look good to me.
This far I added file `/etc/polkit-1/rules.d/60-color-mgr.rules` with the following:
```
polkit.addRule(function(action, subject) {
   if ((action.id == "org.freedesktop.color-manager.create-device" ||
        action.id == "org.freedesktop.color-manager.create-profile" ||
        action.id == "org.freedesktop.color-manager.delete-device" ||
        action.id == "org.freedesktop.color-manager.delete-profile" ||
        action.id == "org.freedesktop.color-manager.modify-device" ||
        action.id == "org.freedesktop.color-manager.modify-profile") &&
       subject.isInGroup("kanyck")) {
      return polkit.Result.YES;
   }
});
```
...which did the trick. That made me think that it's policykit-related issue, but I don't feel it was the proper way to solve it. My understanding that some simple things, like making sure the user is in colord group, should work. But they don't. It worked just fine until last update, so something obviously has changed in the configuration, but I can't find out what it was. Unfortunately, too few docs on xiccd and colord stuff available on the net. They seemingly were supposed "just work", but when they don't -- no idea where to dig... thanks!

**Comment by agalakhov** [comment]
This is not exactly xiccd or colord related, this is how dbus spawns daemons. If some software tries to connect to some dbus service, the corresponding daemon is started according to configuration files in `/etc/dbus-1/` or `/usr/share/dbus-1/`. For example, there is a file saying that for `org.freedesktop.ColorManager` service one has to start `/usr/lib/colord` as `colord` user. There are similar files for disks, cameras, network, passwords, and sometimes even for games. `colord` is just an ordinary dbus service. It is very similar to the configuration of system start-up programs via `systemd`.

**Comment by hughsie** [comment]
> I'm on Gentoo...
> They seemingly were supposed "just work"...

I don't think Gentoo is the distro to choose if you want thing to _just work_... :)
