### ISSUE TITLE
xiccd doesn't kill itself when I log out of XFCE, and xiccd burns my CPU cores.

### ISSUE THREAD

**Issue by crocket** [agalakhov/xiccd#9]
The content of /etc/xdg/autostart/xiccd.desktop

```
[Desktop Entry]
Encoding=UTF-8
Name=xiccd
GenericName=X11 ICC Daemon
Comment=Applies color management profiles to your session
Exec=/usr/bin/sh -c "pgrep xiccd>/dev/null || xiccd"
Terminal=false
Type=Application
Categories=
OnlyShowIn=XFCE;
```

`/usr/bin/sh -c "pgrep xiccd>/dev/null || xiccd"` prevents xiccd from being launched whenever I log in. With this, I don't have multiple xiccd instances after logging out and in multiple times.

I had to devise this workaround because xiccd doesn't kill itself when I log out of XFCE.

The issue is that if I log out and in, the xiccd instance launched by a previous login session occupies 100% of a CPU core. Since I have a quadcore CPU, the minimum CPU usage becomes 25%.

xiccd burns my CPU cores. Please save my CPU cores.

**Comment by agalakhov** [comment]
This is likely to be fixed, please retest it and report if it works for you.

**Comment by crocket** [comment]
I tested it. It is fixed.

**Comment by agalakhov** [comment]
Thank you! Closing.

**Comment by lsdorneles** [comment]
Thanks. (This happened to me after upgrading to Xubuntu 19.10.)

**Comment by terzag** [comment]
With this fix, xiccd doesn't launch for me when first logging in the session.
